---
title: "Using functions in the lmmtools package"
author: "Ari Verbyla"
date: "2024-09-30"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
bibliography: lmmtools.bib
csl: biometrics.csl
vignette: >
  %\VignetteIndexEntry{"Using functions in the lmmtools package"}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## Introduction

The `lmmtools` package consists of several functions that are useful
in the context of mixed model analysis.  This document presents the
workflow for various parts of a mixed model analysis.

## Package data and R scripts

```text
data(package = "lmmtools")
```

The data has also been placed in a second location to provide the ability to
read in manually.  `R` script files for analysis of the data sets are
also in this location.

```text
lmmpath <- system.file("extdata", package = "lmmtools")
list.files(lmmpath)
```

```
[1] "BarleyData.csv" "BarleyFixed.R"  "BarleyRandom.R" "prepData.csv"  
[5] "prepExample.R"  "wheat.R"        "WheatData.csv" 
```

The analyses are conducted using the \code{asreml} package in
\code{R}.  Thus we begin by attaching the `asreml` package and setting
some options.

```text
library(asreml)
asreml.options(Cfixed=TRUE, extra=3)
```

##  The wheat data

The wheat data can be accessed by
```text
library(lmmtools)
data(WheatData, package="lmmtools")
```
The data can also be accessed from a file by
```text
WheatData <- asreml.read.table(paste(lmmpath, "WheatData.csv", sep="/"), header=TRUE, sep=",")
```

The data was presented in @Gilmouretal97 as example 4.1.  The field
trial was almost a complete randomised block design, consisted of 22
rows by 15 columns, with three blocks of 5 columns.  The 107 varieties
were replicated three times (with some standards replicated twice in
each block).  The trait of interest was grain yield (grams per
hectare).  The aim of the analysis was variety selection.

A sequence of 9 models was fitted to the data.  The script file
`wheat.R` in the `extdata` folder or directory, contains the code to
fit the models.  This code is presented here without the resulting
output.

```text
### Models

fm0 <- asreml(yield ~ 1,
              random = ~ Variety + Block,
              data = WheatData)

fm1 <- asreml(yield ~ 1,
              random = ~ Variety + Block,
              residual = ~ ar1(Col):ar1(Row),
              data = WheatData)

fm2 <- asreml(yield ~ 1,
              random = ~ Variety + Block + units,
              residual = ~ ar1(Col):ar1(Row),
              data = WheatData)

fm2 <- update(fm2)

fm3 <- asreml(yield ~ 1,
              random = ~ Variety + Block + Row + Col + units,
              residual = ~ ar1(Col):ar1(Row),
              data = WheatData)

fm4 <- asreml(yield ~ lin(Row) + lin(Col),
              random = ~ Variety + Block + Row + Col + units,
              residual = ~ ar1(Col):ar1(Row),
              data = WheatData)

fm5 <- asreml(yield ~ lin(Row) + lin(Col),
              random = ~ Variety + Block + Row + Col + spl(col) + units,
              residual = ~ ar1(Col):ar1(Row),
              data = WheatData)

fm6 <- asreml(yield ~ Rowcode + Colcode,
              random = ~ Variety + Block + units,
              residual = ~ ar1(Col):ar1(Row),
              data = WheatData)

fm7 <- asreml(yield ~ Rowcode + Colcode,
              random = ~ Variety + Block + Row + Col + units,
              residual = ~ ar1(Col):ar1(Row),
              data = WheatData)

fm8 <- asreml(yield ~ Rowcode + Colcode + lin(Row) + lin(Col),
              random = ~ Variety + Block + Row + Col + units,
              residual = ~ ar1(Col):ar1(Row),
              data = WheatData)

fm9 <- asreml(yield ~ Rowcode + Colcode + lin(Row) + lin(Col),
              random = ~ Variety + Block + Row + Col + spl(col) + units,
              residual = ~ ar1(Col):ar1(Row),
              data = WheatData)

fm9 <- update(fm9)

```
Two models required an update, because parameter estimates were not
fully converged.

It is convenient to place all the models in a list.

```text
fm <- list(fm0=fm0, fm1=fm1, fm2=fm2, fm3=fm3, fm4=fm4, fm5=fm5, fm6=fm6, fm7=fm7,
           fm8=fm8, fm9=fm9)
```
### Heritability

Heritability is often quoted for trials as an indicator of the extent
of the genetic contribution by the varieties tested.  @Oakeyetal06
present a general approach to find the heritability.  This method
works for all situations.  Other methods that have been used in the
literature, are not appropriate for all situations.

In the `lmmtools` package, the function `genherit1` is used to find
the heritability.  The `1` indicates that the function is suitable for
a single trial.  It is possible to use this function when a pedigree
or genomic information is available.  In that case it requires manual
calculation of the appropriate fitted genetic variance covariance
matrix.  This also then allows calculation of both the broad and
narrow sense heritability.

The wheat data does not have a pedigree or genomic information.  Thus
a simple application the `genherit1` function for all the fitted
models is
```text
h2 <- unlist(lapply(fm, function(el) genherit1(el, id="Variety")))
h2
```
with output of the process in `genherit1` not being presented.  The
heritabilities for the models were
```text
fm0.yield fm1.yield fm2.yield fm3.yield fm4.yield fm5.yield fm6.yield fm7.yield 
0.3049775 0.8063624 0.7615973 0.7771553 0.7766496 0.7783054 0.7762049 0.7797931 
fm8.yield fm9.yield 
0.7797122 0.7853669
```
Notice that the heritabilities are very similar, but that a very simple
model, `fm1` has the highest heritability.  In the following
sub-section, we see that the best model is `fm9`.  There have been some
papers that have used heritability for model selection.  This is a
flawed approach.

### icREML

@Gilmouretal97 use residual likelihood ratio tests for model
selection but note that some models cannot be compared in this way
because the fixed effects determine the residual likelihood.  The
models are not nested and to overcome this problem, information
criteria are often used.  @Verbyla19 showed that both the Akaike
Information Criterion (AIC) and the Bayesian or Schwarz Information
Criterion (BIC) can be used using the residual maximum likelihood
estimates of parameters, provided the full log-likelihood is used in
the criteria.

The `icREML` function in `lmmtools` provides way to compare models
using information criteria.  The models need to be in a list, even if
information criteria are required for a single model.  Thus
```text
icREML(list(fm0=fm0))
```
produces
```text
  model res.loglik full.loglik p q b      AIC      BIC
1   fm0  -1753.982   -1758.165 1 3 0 3524.331 3539.527
```
The columns `p`, `q` and `b` indicate the number of fixed effects
parameters, the number of non-boundary variance/covariance/correlation parameters,
and the number of parameters that went to the boundary, respectively.

For the full list of models
```text
selection <- icREML(fm)
selection
```
produces
```text
   model res.loglik full.loglik p q b      AIC      BIC
1    fm0  -1753.982   -1758.165 1 3 0 3524.331 3539.527
2    fm1  -1595.980   -1600.114 1 5 0 3212.229 3235.023
3    fm2  -1564.447   -1568.900 1 5 1 3149.800 3172.595
4    fm3  -1559.824   -1563.932 1 7 1 3143.865 3174.258
5    fm4  -1555.137   -1562.311 3 7 1 3144.623 3182.614
6    fm5  -1551.893   -1556.860 3 8 1 3135.721 3177.511
7    fm6  -1537.052   -1554.226 5 5 1 3128.453 3166.444
8    fm7  -1536.770   -1554.180 5 6 2 3130.361 3172.151
9    fm8  -1531.830   -1552.206 7 6 2 3130.412 3179.801
10   fm9  -1528.631   -1545.605 7 8 1 3121.211 3178.197
```
Model `fm9` has the minimum AIC, while `fm6` has the minimum BIC.
@Gilmouretal97 conclude that model `fm9` is the best fit, which
corresponds to the model with the minimum AIC.

## Two-stage analysis of Multi-environment trials

Two-stage methods for the analysis of multi-environment trials (METs) have
been discussed by a number of authors; see for example
@MohringPiepho09, @Piephoetal12, @Damesaetal17, @Gogeletal18, @Damesaetal19,
@Buntaranetal19, @Endelman23 and @Verbyla23.  This vignette involves
the methods described by @Piephoetal12, @Gogeletal18 and @Verbyla23,
and implemented in the \code{lmmtools} package in `R`, @R24.

### Barley yield trials

The South Australian Barley Program conducted a total of 24 Stage 3
trials over two years, 2006 and 2007.  Randomised complete block
designs were used for all trials, with two or three blocks or
replicates of the varieties.  Within years, the number of common lines
was approximately 180, while between years approximately 50 lines were
in common across pairs of trials.  There were a total of 322 lines
across all the trials, but there was no pedigree or genomic
information.  The aim of the trials was to examine yield performance.
The mean yields (in tonnes/hectare) were highly variable, reflecting
the multi-environment nature of the trials.  The aim of the trials was
promotion of lines to stage 4 trials, and hence best linear unbiased
predictions of variety by environment effects were required, to enable
selection of varieties.

The barley data can be accessed by
```text
data(BarleyData, package="lmmtools")
```
or
```text
### BarleyData <- asreml.read.table(paste(lmmpath, "BarleyData.csv", sep="/"), header=TRUE, sep=",")
```

### Stage 1 analysis of Barley yield

The first stage of analysis of multi-environment trials consists of
analysing each trial separately.  The `stage1` function in `lmmtools`
provides an automatic mechanism for doing these analyses.  However,
this requires the fitting of a base model that is likely to be
suitable for all trials and hence comes with a risk.  It is possible
to add specific terms for individual trials as will be demonstrated for
a wheat yield MET to be presented below.

For the barley data, the call used was
```text
s11 <- stage1(fixed  = yield ~ 1 + lin(Row) + lin(Column),
              random= ~ Genotype + Block + Row + Column,
              residual = ~ ar1v(Column):ar1(Row),
			  Trait="Site", n.trait=1, Genetic="Genotype", 
              data = BarleyData, method = "random", s1trace=TRUE,
			  predict.options=list(ignore=c("lin(Row)", "lin(Column)")))
```
Firstly, we have the usual `fixed`, `random`, and `residual` arguments that
are used in `asreml`.  Note that because of a quirk in `asreml` to do
with the gamma parameterisation, the
residual model **must** be a variance (and not a correlation) model.
Hence the `ar1v` rather than the standard `ar1` for the `Column`
term.  Secondly, linear row and column , and random row and column
effects have been included.  These terms are included to provide for
possible global and extraneous variation as described in
@Gilmouretal97.  There are arguments, `Trait` and `Genetic` which
indicate the factors that are used in the function.  Here `Trait` is
`Site` and the genetic factor is `Genotype`.  The `n.trait` argument
is set to 1 for individual Site analyses.  

The `predict.options` argument allows the user to include arguments for
the predict part of the analyses (which is required to obtain
estimates of genetic effects and their estimated variance-covariance
matrix).  Here we ignore the linear row and column effects, because
the estimated genetic effects will have been adjusted for those components in
the analyses.

After the `stage1` function is run, the object `s11` has the following
components (in a list)
```text
names(s11)
 [1] "call"    "bdVt"    "bdWt"    "V"       "W"       "pred.df" "type"   
 [8] "vc"      "vcMat"   "models" 
```
The `call` is saved, bdVt and bdWt are block diagonal sparse matrices
of the estimated variance-covariance matrix of the genetic effects for
all trials, and it's inverse; `V` and `W` are lists of the individual
matrices for each trial.  The data frame, `pred.df` contains the
estimated genetic effects, standard errors, and a column labelled
`wt`, which is a set of weights, a diagonal approximation to the full
matrix, found by taking the diagonal elements of `bdWt`.  The `type`
is either fixed or random (the latter here).  Note that while the
type states `random`, and the initial estimates of genetic effects are
random, there is a de-regression step as described by @Verbyla23,
which effectively transforms the genetic effects to fixed effects, as
required for the second stage of analysis.  This transformation is not
necessary if the `type` argument is set to `fixed`, but there is
some advantage in using `random`;  see @Verbyla23.

The `vc` argument is simply a list of the summary of the non-genetic variance
parameters for each site analysis, while `vcMat` is a comprehensive
matrix of these components for each site.  Lastly, the `models`
component is a list of all the first stage model objects for each
site analysis.  This can b a very big object so there is an argument,
`keep.models` that can be set to `FALSE` if the models do not need to
be kept.

### Stage 2 analysis of Barley yield

The second stage of analysis involves fitting a sequence of factor
analytic models to incorporate differing variances and correlations
across environments.  A list of models is declared, starting values
setup, and then a model fitted.  The `diag` model for `Site` is fitted
first.  Then it is replaced in sequence by `fa(Site, k)` where `k` is
set from 1 to 9 in this example.

```text
s21.asr <- list()

##############  diag model: starting values

s21.sv <- asreml(yield ~ Site-1, random = ~ diag(Site):Genotype + vm(TG, V11),
                 family = asr_gaussian(dispersion = 0.0001),
                 data=s11$pred.df, start.values=TRUE)

g21 <- s21.sv$vparameters.table
g21
g21$Value[grep("vm\\(", g21$Component)] <- 1
g21$Constraint[grep("vm\\(", g21$Component)] <- "F"
g21

############## Fit the diag model

s21.asr[["diag"]] <- asreml(yield ~ Site-1, random = ~ diag(Site):Genotype + vm(TG, V11),
                  family = asr_gaussian(dispersion = 0.0001),
                  data=s11$pred.df,
                  maxit=200, G.param=g21, workspace="20Gb")
				  
###############  fa1 model

s21.sv <- asreml(yield ~ Site-1, random = ~ fa(Site, 1):Genotype + vm(TG, V11),
                 family = asr_gaussian(dispersion = 0.0001),
                 data=s11$pred.df, start.values=TRUE)

g21 <- s21.sv$vparameters.table
g21
g21$Value[grep("vm\\(", g21$Component)] <- 1
g21$Constraint[grep("vm\\(", g21$Component)] <- "F"
g21

s21.asr[["fa1"]] <- asreml(yield ~ Site-1, random = ~ fa(Site, 1):Genotype + vm(TG, V11),
                  family = asr_gaussian(dispersion = 0.0001),
                  data=s11$pred.df,
                  maxit=200, G.param=g21, workspace="20Gb")
```
and so on for fa2 to fa9 models that were fitted.  For more detail see `twostageRandom.R` in the `extdata` folder.

Using the diagonal approximation to the full weight matrix is also
possible, but note that this in general is inferior to using the full
weight matrix.  The diagonal approximation is typically used when the
data set is large, because fitting is then too slow if using the full
weight matrix.  The corresponding code if diagonal weights are used is
```text
s21d.asr <- list()

s21d.asr[["diag"]] <- asreml(yield ~ Site-1, random = ~ diag(Site):Genotype,
                   weights = wt, family = asr_gaussian(dispersion = 1),
                   data=s11$pred.df,
                   maxit=50, workspace="20Gb")
```
with `diag` replaced by fa1 to fa9 models as for the analysis with a
full weight matrix.

### Application of the fmSummary function

Having fitted a sequence of models, there is the question of model
selection.  The `faSummary` function provides a summary of the models
fitted, with residual log-likelihood, a sequential likelihood ratio
statistic (REMLRS),
with degrees of freedom and p-value, the residual likelihood based
Akaike Information Criterion (AIC), the Bayesian Information Criterion
(BIC) and some summary measures to indicate relative changes in
aspects of the models.  These are, percentage of total variance
explained by the factors (perc.var), the relative Frobenius norm (fn) of
the difference of the current variance model (vm) and the previous
variance model, relative to the previous variance
model, (fn.vm), the Meyer statistic, the Euclidean norm of the
change in estimated variances relative to the previous variance model,
and the Frobenius norm of the difference of the current and previous
estimated correlation matrices, relative to the Frobenius norm of the  previous
estimated correlation matrix (fn.corr).

For this MET, the REMLRS suggests either the fa6 or the fa8 model is
appropriate.  Note that in this analysis, this statistic is not
monotone as the number of factors increases.  The AIC suggests the fa4
is sufficient, while the BIC suggests only an fa2 is required.  Note
that various norms suggest that stability of the full variance matrix
and correlation matrix in terms of percentage change is probably
at least the fa4 model.  Both the Meyer statistic and the relative norm
for the variances are very stable over all models.  

```text

faSummary(s21.asr, data=s11$pred.df, "Site", id = "Genotype")
     model  loglik seq.lrt df   pval      AIC      BIC perc.var  fn.vm meyer
diag  diag 3544.55      NA NA     NA -7041.09 -6888.07       NA     NA  1.89
fa1    fa1 4646.01 2202.93 26 0.0000 -9192.03 -8873.22    44.85 156.20  1.86
fa2    fa2 4962.73  633.43 24 0.0000 -9777.45 -9305.62    69.39  41.42  1.86
fa3    fa3 5058.92  192.38 24 0.0000 -9921.83 -9296.97    73.72   9.48  1.84
fa4    fa4 5088.79   59.75 24 0.0001 -9933.58 -9155.69    75.83   8.19  1.85
fa5    fa5 5110.45   43.33 24 0.0091 -9928.91 -8998.00    81.58   7.81  1.85
fa6    fa6 5134.47   48.02 24 0.0025 -9928.93 -8845.00    82.31   8.69  1.84
fa7    fa7 5145.94   22.94 24 0.5232 -9903.87 -8666.91    85.01   6.66  1.85
fa8    fa8 5161.88   31.89 24 0.1296 -9887.77 -8497.78    87.97   8.75  1.85
fa9    fa9 5172.73   21.69 24 0.5978 -9861.46 -8318.45    89.18   4.63  1.85
     norm.var fn.cor
diag       NA     NA
fa1      2.43 249.50
fa2      1.21  30.08
fa3      1.78  10.35
fa4      2.30   7.07
fa5      0.60   4.64
fa6      1.55   7.73
fa7      1.07   5.79
fa8      1.87   7.98
fa9      1.20   5.22
```

### Wheat MET with partial replication

This example is a MET with four sites, each partially replicated.  We
begin by attaching the required libraries and setting options for `asreml`.

```text
require(asreml)
require(lmmtools)
asreml.options(Cfixed=TRUE, extra=3, ai.sing=TRUE)
```

The data set can be accessed using
```text
data(prepData)
```

### Stage 1 analysis

The first stage of analysis proceeds as for the `barley` data.  However,
there are some additional features of this data that the `stage1`
function provides.  Firstly, for Sites 3 and 4 (second year of the
trials), there are phenology groups present in the data.  The
`PhenoGroup` factor is declared as being specific to Sites 3 and 4
using the `specific` argument.  It is a fixed effect.  For the second
stage of analysis, this needs to be removed when the de-regression
(here the argument `type` is `random` as it is the default), and hence
the `predGenetic` argument allows specification of the removal using
the `rm` component.  This argument also specifies the genetic factor
and optionally the classify factor (the default is the same as the
`id` argument), that will be used in the de-regression fit.  Lastly,
there are predict options that can be specified using
`predict.options`.

Both `Genetic` and `Trait` arguments are as for the `barley` data.

```text
s11 <- stage1(yield ~ 1 + lin(Row) + lin(Column),
random = ~ mpid + Block + Row + Column,
             residual = ~ ar1v(Column):ar1(Row),
             data=prepData, Trait="Site", Genetic = "mpid",
             specific = list(PhenoGroup = list(type="fixed", which=3:4)),
             predGenetic=list(id = "mpid", classify = "mpid",
			                  rm = list(list(terms = "PhenoGroup", which=3:4))),
             predict.options=list(ignore = c("lin(Row)", "lin(Column"),
			                      pworkspace="5GB"),
             na.action = na.method(x="include"), keep.models=TRUE,
             s1trace=FALSE, workspace = "5GB")
```
The first stage results in two important components, as for the
`barley` data.  Firstly, the variance matrix is extracted from the
`s11` object.
```text
V11 <- as.matrix(s11$bdVt)
```
This is now included as the residual term using `vm` in `asreml`.  The
data for the second stage analysis is in `s11$pred.df`.  

Staring values are set up,
```text
s21.sv <- asreml(yield ~ Site-1, random = ~ corgh(Site):mpid + vm(TG, V11),
                  family = asr_gaussian(dispersion = 0.0001),
                  data=s11$pred.df,
                  start.values=TRUE)
```
and the `vm` term constrained to have unit variance and `F`ixed.
```text
g2 <- s21.sv$vparameters.table
g2
g2$Value[grep("vm\\(TG", g2$Component)] <- 1
g2$Constraint[grep("vm\\(TG", g2$Component)] <- "F"
```
Using the starting values in `g2`, the second stage analysis can now proceed.

```text
s21.asr <- asreml(yield ~ Site-1, random = ~ corgh(Site):mpid + vm(TG, V11),
                  family = asr_gaussian(dispersion = 0.0001),
                  data=s11$pred.df,
                  G.param=g2, workspace="10Gb", maxit=30)
```
A summary of the variance parameters can be found using
```text
summary(s21.asr)$varcomp
```
and produces
```text
                              component  std.error   z.ratio bound %ch
vm(TG, V11)                  1.00000000         NA        NA     F   0
Site:mpid!Site!2:!Site!1.cor 0.07594544 0.05968759  1.272382     U   0
Site:mpid!Site!3:!Site!1.cor 0.83152884 0.03600421 23.095323     U   0
Site:mpid!Site!3:!Site!2.cor 0.43710182 0.04881442  8.954358     U   0
Site:mpid!Site!4:!Site!1.cor 0.18279776 0.05813619  3.144302     U   0
Site:mpid!Site!4:!Site!2.cor 0.78479584 0.03230489 24.293408     U   0
Site:mpid!Site!4:!Site!3.cor 0.61519378 0.04058417 15.158466     U   0
Site:mpid!Site_1             0.13702933 0.01084824 12.631479     P   0
Site:mpid!Site_2             0.23073430 0.01742860 13.238835     P   0
Site:mpid!Site_3             0.23960804 0.01751181 13.682654     P   0
Site:mpid!Site_4             0.16426024 0.01136456 14.453731     P   0
units!R                      0.00010000         NA        NA     F   0
```
Predictions of variety effects and any other features could now be carried
out.

###  Diagonal weights

Diagonal weights are usually sub-optimal, as was pointed out for the
`barley` data, but there are situations where the size of the problem
prohibits the full weight matrix. Fitting the stage 2 model with
diagonal weights can be achieved for this data by
```text
s21d.asr <- asreml(yield ~ Site-1, random = ~ corgh(Site):mpid,
                  family = asr_gaussian(dispersion = 1), weights = wt,
                  data=s11$pred.df,
                  workspace="10Gb", maxit=30)
```
and the summary of the variance parameters can be displayed using
```text
summary(s21d.asr)$varcomp
```
Note that in this case the estimated variance parameters are similar to,
but not the same as, using the full weight matrix.
```text
                              component  std.error   z.ratio bound %ch
Site:mpid!Site!2:!Site!1.cor 0.09676608 0.05624874  1.720324     U   0
Site:mpid!Site!3:!Site!1.cor 0.83444938 0.03505235 23.805804     U   0
Site:mpid!Site!3:!Site!2.cor 0.41606340 0.04618932  9.007784     U   0
Site:mpid!Site!4:!Site!1.cor 0.13820778 0.05670395  2.437357     U   0
Site:mpid!Site!4:!Site!2.cor 0.74962332 0.03055817 24.531030     U   0
Site:mpid!Site!4:!Site!3.cor 0.56269483 0.04101417 13.719523     U   0
Site:mpid!Site_1             0.13549693 0.01074795 12.606765     P   0
Site:mpid!Site_2             0.25898522 0.01824981 14.191116     P   0
Site:mpid!Site_3             0.24553294 0.01777902 13.810263     P   0
Site:mpid!Site_4             0.17879251 0.01190211 15.021912     P   0
units!R                      1.00000000         NA        NA     F   0
```
###  Heritabilities at stage 1

Because the `keep.models` argument is set to `TRUE`, it is possible to
find heritabilities for each of the trials.

```text
h2 <- unlist(lapply(s11$models, function(el) genherit1(el, id = "mpid")))
h2
```

```text
  1.yield   2.yield   3.yield   4.yield 
0.6464116 0.6324765 0.7477038 0.7866346 
```

## Further developments

Some of the functionality of the `lmmtools` package is still being
developed.  The package and this vignette will be updated accordingly.


## References
